members/descuentosProyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls.i18n import i18n_patterns

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]

#urlpatterns += i18n_patterns(
#	path('', include('descuentosApp.urls')),
	
#)

urlpatterns = [
	
	path('admin/', admin.site.urls),
	path('', include('descuentosApp.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('shop/', include('tienda.urls')),
    path('staff/', include('adminErasmus.urls')),
    path('i18n/', include("django.conf.urls.i18n")),

    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/members/urls.py
from django.urls import path
from . import views
from .views import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required


urlpatterns = [


	path('register/', views.NewUserRegistrationView, name='UserRegistrationView'),
	

	path('login/', views.Login, name='Login'),
	path('userprofile/', views.UserProfile, name='UserProfile'), 
	path('edituserprofile/', login_required(EditProfile.as_view()), name='EditUserProfile'), 
	path('password/', login_required(PasswordChangeView.as_view(template_name = 'profile/change_password.html')), name='ChangePassword'),
   # path('register/', views.Register, name='Register'),

	# Validate Email
	path('activate/<uidb64>/<token>', Verification.as_view(), name='ActivateAcount' ),


	#Reseteo de la contra via email: 
	path('reset_password/', auth_views.PasswordResetView.as_view(template_name = 'profile/email_password_reset.html'), name="reset_password"),
	path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = 'profile/password_reset_sent.html' ), name="password_reset_done"), 
	path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'profile/password_reset_form.html'), name="password_reset_confirm"),
	path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'profile/password_reset_done.html'), name="password_reset_complete"), 
]

members/tienda/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [


    path('tienda/', views.Tienda, name='Tienda'),
	path('carrito/', views.Carrito, name='Carrito'),
    path('checkout/', views.Checkout, name='Checkout'),
    path('producto/<int:pk>', views.ProductDetail.as_view(), name='ProductDetail'),
    path('update_item/', views.updateItem, name='update_item'),
    
    path('process_order/', views.processOrder, name='processOrder'),

    
]

members/members/models.py
from datetime import date 
from django.db import models
from django.db.models.fields import NullBooleanField
from django.urls.base import reverse

from descuentosApp.models import Country, City, University, Guide
from django.core.validators import RegexValidator

from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    
    date = models.DateField(default="2020-01-01")

    date_inicio = models.CharField(max_length=8, default="")
    
    date_fin = models.CharField(max_length=8, default="")
    
    GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'), ('U', 'Unisex'))
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, null=False)

    COURSE_CHOICES = (('Primero', '1'), ('Segundo', '2'), ('Tercero', '3'), ('Cuarto', '4'), ('Quinto', '5'), ('Sexto', '6'))
    course = models.CharField(max_length=7, choices=COURSE_CHOICES, blank=True, null=True)

    country =  models.ForeignKey(Country, on_delete=models.CASCADE)
    phone = models.IntegerField(null=True, )
    prefix = models.IntegerField(null=True )
    STUDENT_CHOICES = (('1', 'Bachelor'), ('2', 'Au Pair'), ('3', 'Master'), ('4', 'Internship'))
    studentType = models.CharField(max_length=10, choices=STUDENT_CHOICES, null=True, default='')
    cityOrigin1 =  models.CharField(max_length=10, blank=True, null=True)
    cityDestination1 =  models.CharField(max_length=50, null=False)
    cityDestination2 =  models.CharField(max_length=50, blank=True)
    cityDestination3 =  models.CharField(max_length=50, blank=True)
    universityOrigin =  models.CharField(max_length=50,null= True, blank=True)
    universityDestination =  models.CharField(max_length=50, null=True, blank=True)
    studies =  models.CharField(max_length=50, null=True, blank=True)
    #course =  models.CharField(max_length=50, null= True, blank=True)
    company = models.CharField(max_length=50,null= True, blank=True)

    def calcularEdad(self, edadintroducida):
        hoy = date.today()
        edad = hoy.year - edadintroducida.year - ((hoy.month, hoy.day) < (edadintroducida.month, edadintroducida.day))

        return edad
    def get_absolute_url(self):
    #return reverse('article-detail', args=(str(self.id)))
     return reverse('base')

    def __str__(self):
        return self.username
   

members/members/forms.py
from descuentosApp.models import Country, University
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm, UserCreationForm

from members.models import User
from django import forms
from .models import City, Country




# Cargar SubCategorias
choices_sub = City.objects.all().values_list('name', 'name')
city_list = []

for item in choices_sub:
	city_list.append(item)


choices_country = Country.objects.all().values_list('name', 'name')
country_list = []

for item in choices_country:
	country_list.append(item)

#generos
gender_list=['Male ', 'Female', 'Unisex']

course_list=['1 ', '2', '3', '4 ', '5', '6']

class SignUpForm(UserCreationForm):
	email =forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
	first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
	last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
	city = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name','city', 'email', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)
			  
		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['class'] = 'form-control'


STUDENT_CHOICES = (('1', 'Bachelor'), ('2', 'Au Pair'), ('3', 'Master'), ('4', 'Internship')),

class CreateUserForm(UserCreationForm):
	
	
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'date' , 'date_inicio', 'date_fin', 'gender' ,'country', 'phone', 'prefix', 'studentType', 'cityOrigin1',
		 'cityDestination1', 'cityDestination2', 'cityDestination3', 'universityOrigin', 'universityDestination', 'studies', 'email', 'password1', 'password2', 'course', 'company']
		
		def __init__(self, *args, **kwargs):
			super(CreateUserForm, self).__init__(*args, **kwargs)
			# asi vuelves tus campos no requeridos
			self.fields['course'].required = False

		widgets ={
			
            'cityDestination1': forms.Select(choices=city_list, attrs={'class':'form-control '}),
			'cityDestination2': forms.Select(choices=city_list, attrs={'class':'form-control '}),
			'cityDestination3': forms.Select(choices=city_list, attrs={'class':'form-control '}),
			'cityOrigin1': forms.Select(choices=city_list, attrs={'class':'form-control '}),
			'universityOrigin': forms.Select(attrs={'class':'form-control '}),
			'studentType': forms.TextInput(attrs={'class':'form-control ', 'value': '', 'type': 'hidden'}),
			'universityDestination': forms.Select(attrs={'class':'form-control '}),
			'country': forms.Select(choices=country_list, attrs={'class':'form-control '}),
			'gender': forms.Select(choices=gender_list, attrs={'class':'form-control '}),
			'first_name': forms.TextInput(attrs={'class':'form-control '}),
			'last_name': forms.TextInput(attrs={'class':'form-control '}),
			'date': forms.DateInput(attrs={'class':'form-control ', 'type' :'date'}),
			'username': forms.TextInput(attrs={'class':'form-control '}),
			'email': forms.EmailInput(attrs={'class':'form-control ', 'placeholder': 'name@example.com'}),
			'prefix': forms.TextInput(attrs={'class':'form-control ', 'placeholder': '+34'}),
			'phone': forms.TextInput(attrs={'class':'form-control '}),
			'studies': forms.TextInput(attrs={'class':'form-control ', 'placeholder': 'Example: Business Administration'}),
			'course': forms.Select(choices=course_list, attrs={'class':'form-control '}),
			'company': forms.TextInput(attrs={'class':'form-control '}),
			'date_inicio': forms.TextInput(attrs={'class':'form-control ', 'placeholder': '05/2021'}),
			'date_fin': forms.TextInput(attrs={'class':'form-control ', 'placeholder': '12/2021'}),
			

		
		}

university_choices = University.objects.all().values_list('name', 'name')
university_list = []

for uni in university_choices:
	university_list.append(uni)

class EditUserForm(UserChangeForm):
	
	
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'date' , 'gender' ,'country', 'phone', 'studentType', 'cityOrigin1',
		 'cityDestination1', 'cityDestination2', 'cityDestination3', 'universityOrigin', 'universityDestination', 'studies', 'email', 'course', 'company']
		
			  

		widgets ={
			
            'cityDestination1': forms.Select(choices=city_list, attrs={'class':'form-control '}),
			'cityDestination2': forms.Select(choices=city_list, attrs={'class':'form-control '}),
			'cityDestination3': forms.Select(choices=city_list, attrs={'class':'form-control '}),
			'cityOrigin1': forms.Select(choices=city_list, attrs={'class':'form-control '}),
			'universityOrigin': forms.Select(choices=university_list,attrs={'class':'form-control '}),
			'studentType': forms.TextInput(attrs={'class':'form-control ', 'value': '', 'type': 'hidden'}),
			'universityDestination': forms.Select(choices=university_list,attrs={'class':'form-control '}),
			'country': forms.Select(choices=country_list, attrs={'class':'form-control ', 'default':False}),
			'gender': forms.Select(choices=gender_list, attrs={'class':'form-control '}),
			'first_name': forms.TextInput(attrs={'class':'form-control ', 'placeholder': 'First name...'}),
			'last_name': forms.TextInput(attrs={'class':'form-control ', 'placeholder': 'Last name...'}),
			'date': forms.DateInput(attrs={'class':'form-control ', 'type' :'date', 'placeholder': 'Birthday...'}),
			'username': forms.TextInput(attrs={'class':'form-control ', 'placeholder': 'Username...'}),
			'email': forms.EmailInput(attrs={'class':'form-control ', 'placeholder': 'Email...'}),
			'phone': forms.TextInput(attrs={'class':'form-control ', 'placeholder': 'Phone number...'}),
			'studies': forms.TextInput(attrs={'class':'form-control ', 'placeholder': 'Studies...'}),
			'course': forms.TextInput(attrs={'class':'form-control ', 'placeholder': 'Course...'}),
			'company': forms.TextInput(attrs={'class':'form-control ', 'placeholder': 'Company...'}),
			

		
		}



# Form para cambiar la contra
class ChangePassword(PasswordChangeForm):

	pedido_de =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '*****'})),
	pedido =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '*****'})),
	direccion =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '*****'})),
	new_password2 =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '*****'})),
	new_password1 =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '*****'})),
	new_password1 =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '*****'})),
	new_password1 =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '*****'})),
	new_password1 =  forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '*****'})),

	class Meta:
		model = User
		fields = ['pedido_de', 'pedido', 'direccion', 'ciudad', 'provincia', 'codigo_postal', 'date_added' ]

members/members/views.py
from django.contrib.auth.decorators import login_required
from django.core.checks import messages
from django.http import request
from django.urls.base import reverse
from django.urls.conf import path
from descuentosApp.models import Country
from django.shortcuts import render, redirect
from django.views.generic import *
from django.contrib.auth.forms import *
from django.urls import reverse_lazy
from .forms import *
from .models import User
from django.contrib.auth  import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.core.mail import EmailMessage


# Imports para el email verification

from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site
from .utils import token_generator






def NewUserRegistrationView(request):
    error = False
    form = CreateUserForm()
    if request.method == 'POST':

        form = CreateUserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.is_active = False
            edadintro = instance.date
            edad = instance.calcularEdad(edadintro)

            if (edad > 18):
                
                instance.save()

                

                # Email
                email_subject = 'Activate your account'
                # Path a la ventana

                uidb64 = urlsafe_base64_encode(force_bytes(instance.pk))

                domain = get_current_site(request).domain
                link = reverse('ActivateAcount', kwargs = {'uidb64': uidb64, 'token': token_generator.make_token(instance)})
                activate_url = 'http://'+domain+link
                email_body = 'Hola' + instance.username + 'please, use this link to validate your email\n' + activate_url
                email = EmailMessage(
                    email_subject, 
                    email_body,
                    'noreply@semycolon.com', 
                    [instance.email],
                    
                )
                email.send(fail_silently=True)

                return redirect ('base')
            else: 
                error = True

    context = {'form': form, 'error': error}
    return render (request, 'registration/registration.html', context)



class Verification(View):
    def get(self, request, uidb64, token):


        try:
            id=force_text(urlsafe_base64_decode(uidb64))
            user=User.objects.get(pk=id)

            if not token_generator.check_token(user, token):
                return redirect('Login' + '?message=' + 'User al ready activated')


            if user.is_active:
                return redirect('Login')

            user.is_active = True 
            user.save()

            messages.success(request, 'Account activated sucesfully')
            return redirect('Login')

        except Exception as ex:
            pass



        
        return redirect('Login')











def Login(request):

  
    if request.method == 'POST':

        if request.POST.get('submit') == 'sign_in':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('base')



    return render(request, 'registration/login.html')


 





@login_required
def UserProfile(request):

    return render(request, 'profile/userProfile.html')


class EditProfile(UpdateView):

    form_class = EditUserForm
    template_name = 'profile/edit_profile.html'
    success_url = reverse_lazy('base') #METER PLANTILLA DE SUCCESFULL EDIT.
    
    

    def get_object(self):
        return self.request.user



class PasswordChangeView(PasswordChangeView):

    form_class = ChangePassword
    template_name = 'perfil/change_password.html'
    succes_url = reverse_lazy('Index')
    

members/members/templates/profile/change_password.html
{% extends 'index.html' %}

{% block content %}

{%load static%}
        <!--header starts-->
        <header class="header transparent scroll-hide">
            <!--Main Menu starts-->
            <div class="site-navbar-wrap v1 headerColor">
                <div class="container">
                    <div class="site-navbar">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-md-3 col-6">
                                <a class="navbar-brand logoEP" href="{% url 'base' %}"><img src="{%static 'images/EPCircularBlanco.png' %}" alt="logo" class="img-fluid"></a>
                            </div>
                            <div class="col-xl-9 col-md-9 col-6">
                                <nav class="site-navigation float-left">
                                    <div class="container">
                                        <ul class="site-menu js-clone-nav d-none d-lg-block">
                                            <li>
                                                <a href="{%url 'Alojamiento' %}">Alojamiento</a>
                                            </li>
                                            <li>
                                                <a href="#">Red Social</a>
                                            </li>
                                            <li>
                                                <a href="https://www.what2do.click/" target="_blank">Ocio</a>                                              
                                            </li>
                                            <li>
                                                <a href="{% url 'Descuentos' %}">Descuentos</a>
                                            </li>  
                                            
                                            <li class="d-lg-none">
                                                asd
                                            </li>
                                        </ul>                                                        
                                    </div>
                                </nav>

                                <!-- ICONO MENÚ RESPONSIVE -->
                                <div class="d-lg-none sm-right">
                                    <a href="#" class="mobile-bar js-menu-toggle">
                                        <span class="ion-android-menu"></span>
                                    </a>
                                </div>
                                <!--  -->

                            
                            </div>
                        </div>   
                    </div>
                    <!--mobile-menu starts -->
                    <div class="site-mobile-menu">
                        <div class="site-mobile-menu-header">
                            <div class="site-mobile-menu-close  js-menu-toggle">
                                <span class="ion-ios-close-empty"></span>
                            </div>
                        </div>
                        <div class="site-mobile-menu-body"></div>
                    </div>
                    <!--mobile-menu ends-->
                </div>
            </div>
            <!--Main Menu ends-->
        </header>
        <!--User Login section starts-->
        <div class="user-login-section section-padding bg-fixed">
            <div class="container margenTop50">
                <div class="row">
                    <div class="col-md-10 offset-md-1  text-center">
                        <div class="login-wrapper anchoRegistro">
                        <div class="imgLogo">
                            <img src="{% static 'images/EPCircularTexto.png' %}">
                        </div>
                        <div class="textoDegradado">
                            <h3 class="margen50">Change your password.</h3>
                        </div>
                            <div class="ui-dash tab-content">
                                <div class="tab-pane fade show active" id="login" role="tabpanel">
                                    <form method="POST">
                                        {% csrf_token %}
                                        <div class="card-body">
                                            <div class="form-group mb-8">
                                                <div class="alert alert-custom alert-default" role="alert">
                                                    <div class="alert-icon"><i class="flaticon-warning text-primary"></i></div>
                                                    <div class="alert-text">
                                                        {{user.username}}, you are about to change the password.
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Contraseña actual <span class="text-danger">*</span></label>
                                                {{form.old_password}}
                                                <span class="form-text text-muted">Esta contraseña va a desaparecer.</span>
                                            </div>
                                            <div class="form-group">
                                                <label for="exampleInputPassword1">Contraseña nueva <span class="text-danger">*</span></label>
                                                {{form.new_password1}}
                                            </div>
                        
                                            <div class="form-group">
                                                <label for="exampleInputPassword1">Confirmar contraseña <span class="text-danger">*</span></label>
                                                {{form.new_password2}}
                                            </div>
                                            
                                            {{form.errors}}
                                        </div>
                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                                            
                                        </div>
                                    </form>

                                  
                                </div>

                               
                                {{form.errors}}
                            

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--User login section ends-->
        <!--Login section ends-->
        <!-- Scroll to top starts-->
        <span class="scrolltotop"><i class="ion-arrow-up-c"></i></span>
        <!-- Scroll to top ends-->
    {% endblock %}

members/members/templates/profile/password_reset_done.html
{% extends 'index.html' %}

{% block content %}

{%load static%}

        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class="container">
                <!--begin::Profile Personal Information-->
                <div class="card card-custom">
                    <div class="card-header">
                        <h3 class="card-title">
                            Contraseña para el usuario {{user.username}}
                        </h3>
                        <div class="card-toolbar">
                            <div class="example-tools justify-content-center">
                                <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                                <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->

                    <div class="card-body">
                        <div class="form-group mb-8">
                            <div class="alert alert-custom alert-default" role="alert">
                                <div class="alert-icon"><i class="flaticon-warning text-primary"></i></div>
                                <div class="alert-text">
                                    La contraseña ha sido actualizada correctamente.
                                </div>
                            </div>
                        </div>



                    </div>
                    <div class="card-footer">
                        <a href="{% url 'Login' %}"><button type="submit"
                                class="btn btn-primary mr-2">Login</button></a>

                    </div>

                    <!--end::Form-->
                </div>
                <!--end::Profile Personal Information-->
            </div>
            <!--end::Container-->
        </div>

        {% endblock %}

members/members/templates/profile/userProfile.html
{% extends 'index.html' %}

{% block content %}

{%load static%}

  
<!--Dashboard breadcrumb starts-->
<div style="width: 60% !important; margin:0 auto;">
            <div class="dash-breadcrumb">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            
                        </div>
                    </div>
                </div>
            </div>
            <!--Dashboard breadcrumb ends-->
            <!--Dashboard content starts-->
            <div class="dash-content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-10 offset-md-1">
                            <div class="recent-activity">
                                <div class="act-title">
                                    <h5><i class="ion-person"></i>Profile Details</h5>
                                </div>
                                <div class="profile-wrap">
                                    <div class="row">
                                        <div class="col-md-8 offset-md-2">
                                            <div class="edit-profile-photo text-center mt-3">
                                                <img src="{%static 'images/clients/reviewer-4.png'%}" alt="">
                                            </div>
                                            
                                        </div>
                                        <div class="col-md-12">
                                            <div class="my-profile">
                                                <ul class="db-profile-info float-left">
                                                    <li>
                                                        <h6>Username :</h6>
                                                        <span>{{user.username}} </span>
                                                    </li>
                                                    <li>
                                                        <h6>First Name :</h6>
                                                        <span>{{user.first_name}} </span>
                                                    </li>
                                                    <li>
                                                        <h6>Last Name :</h6>
                                                        <span> {{user.last_name}}</span>
                                                    </li>
                                                    <li>
                                                        <h6>Email Id :</h6>
                                                        <span> {{user.email}}</span>
                                                    </li>                                                   
                                                </ul>

                                                <ul class="db-profile-info float-right">   
                                                    <li>
                                                        <h6>Country :</h6>
                                                        <span> {{user.country}}</span>
                                                    </li>
                                                  
                                                    <li>
                                                        <h6>Phone :</h6>
                                                        <span> +{{user.country.id}} - {{user.phone}}</span>
                                                    </li>
                                                  
                                                    <li>
                                                        <h6>Student Type :</h6>
                                                        <span> {{user.get_studentType_display}}</span>
                                                    </li>
                                                    <li>
                                                        <a href="{% url 'EditUserProfile'%}" class="btn v3 botonAzul">Edit profile</a>
                                                        <a href="{% url 'ChangePassword' %}" class="btn v3 botonAzul">Change password
                                                        </a>
                                                    </li>
                                                    
                                                </ul>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--Dashboard content ends--></div>
  <!-- Scroll to top starts-->
<span class="scrolltotop"><i class="ion-arrow-up-c"></i></span>
<!-- Scroll to top ends-->

<!--Page Wrapper ends-->
{% endblock %}